export {
  DEFAULT_HOKUSAI_BASE_URL,
  DEFAULT_ROUTER_MODEL_ID,
  HokusaiApiError,
  HokusaiAuthError,
  HokusaiClient,
  HokusaiDispatchBuilder,
  HokusaiDispatchError,
  HokusaiNetworkError,
  HokusaiRateLimitError,
  HokusaiValidationError,
  SDK_VERSION,
  createGatedClient,
  type ContributionAcceptedResponse,
  type ContributionRequest,
  type ContributionRequestMetadata,
  type FetchTransport,
  type FetchTransportRequestInit,
  type FetchTransportResponse,
  type GatedClient,
  type HokusaiClientOptions,
  type HokusaiDispatchBuilderOptions,
  type HokusaiPluginClientOptions,
  type HokusaiRequestOptions,
  type HokusaiRouteOptions,
  type HokusaiSignalRequest,
  type HokusaiSignalResponse,
} from './client.js';
export {
  ConfigValidationError,
  FilePluginConfigStore,
  LocalStorePluginConfigStore,
  defaultPluginConfigPath,
  loadPluginConfig,
  redactPluginConfig,
  summarizeAllowlist,
  type HokusaiPluginConfig,
  type LoadPluginConfigOptions,
  type PluginConfigOverrides,
  type PluginConfigStore,
  type PluginConfigStored,
  type RedactedPluginConfig,
} from './config.js';
export {
  DEFAULT_ROUTING_OBJECTIVE,
  ROUTING_OBJECTIVES,
  parseRoutingObjective,
  routingObjectiveToApiValue,
  type RoutingObjective,
  type RoutingObjectiveApiValue,
} from './routing-objective.js';
export {
  ROUTING_ROLES,
  classifyRoutingPools,
  effectiveRolePool,
  resolveRoutingInput,
  singletonRoles,
  validateRoutingInput,
  type ResolveRoutingInputOptions,
  type ResolvedRoutingInput,
  type RouteRoutingInput,
  type RoutingCandidatePools,
  type RoutingMode,
  type RoutingPoolFidelity,
  type RoutingRole,
} from './routing-inputs.js';
export {
  anonymizeText,
  DEFAULT_REDACTION_CONFIG,
  hashPayload,
  makePlaceholder,
  preview,
  redact,
  type AnonymizationOptions,
  type AnonymizedText,
  type CustomRedactionRule,
  type PreviewResult,
  type RedactionCategory,
  type RedactionConfig,
  type RedactionMatch,
  type RedactionMode,
  type RedactionRecord,
  type RedactionPattern,
  type RedactionResult,
} from './anonymization.js';
export {
  ConsentRequiredError,
  assertCanRoute,
  assertCanSubmitOutcome,
  canReportOutcome,
  canRoute,
  canRouteWithAuth,
  canSubmitOutcomeWithAuth,
  isConsentGranted,
  resolveConsent,
  type ConsentConfig,
  type ConsentRequiredReason,
  type ConsentRequiredScope,
  type ConsentSettings,
  type ConsentScope,
  type ConsentSnapshot,
  type HokusaiApiConfig,
  type PayloadPreviewSettings,
  type RetentionPolicy,
} from './consent.js';
export type {
  AdapterError,
  AdapterResult,
  HarnessAdapter,
  HarnessConsentDecision,
  HarnessConsentDecisionState,
  HarnessConsentPromptRequest,
  HarnessConsentPrompter,
  HarnessDiscoveredModel,
  HarnessLocalStorage,
  HarnessModelDiscoveryRequest,
  HarnessModelHandoff,
  HarnessModelHandoffRequest,
  HarnessModelHandoffResult,
  HarnessModelMappingRequest,
  HarnessModelProvider,
  HarnessOutcomeCollectionRequest,
  HarnessOutcomeCollector,
  HarnessPayloadPreview,
  HarnessPayloadPreviewRequest,
  HarnessPayloadPreviewer,
  HarnessRecommendation,
  HarnessRecommendationDisplayRequest,
  HarnessRecommendationRenderer,
  HarnessTaskContext,
  HarnessTaskContextProvider,
  HarnessTaskContextRequest,
} from './adapter.js';
export {
  ANTHROPIC_MODELS,
  InMemoryModelRegistry,
  ModelMappingError,
  OPENAI_MODELS,
  OPENROUTER_PRIORITY_MODELS,
  PRIORITY_MODELS,
  listSupportedModelIds,
  mapRecommendation,
  validateRecommendedModel,
  type MapRecommendationOptions,
  type ModelCapability,
  type ModelDefinition,
  type ModelMappingErrorCode,
  type ModelRegistry,
  type ModelSelection,
  type ValidateRecommendedModelResult,
} from './model-registry.js';
export {
  buildHandoffInstructions,
  type BuildHandoffInstructionsInput,
  type HandoffInstructions,
} from './handoff.js';
export {
  createDefaultHandoff,
  createDefaultOutcomeReport,
  createFsStore,
  executeRouteCommand,
  latestRouteCommand,
  previewOutcomeCommand,
  privacyStatusCommand,
  submitOutcomeCommand,
  type ExecuteRouteCommandInput,
  type LatestRouteCommandValue,
  type PreviewOutcomeCommandInput,
  type PreviewOutcomeCommandValue,
  type PrivacyStatusCommandValue,
  type RouteCommandValue,
  type SubmitOutcomeCommandInput,
  type SubmitOutcomeCommandValue,
} from './harness-commands.js';
export {
  recordOnboardingFunnelSignal,
  type OnboardingFunnelSignal,
  type OnboardingFunnelStage,
  type RecordOnboardingFunnelSignalInput,
} from './onboarding-funnel.js';
export type {
  HarnessCommandError,
  HarnessCommandResult,
  HarnessRoutingProfile,
} from './harness-profile.js';
export {
  checkApiKey,
  checkApiKeyAccepted,
  checkApiReachability,
  checkDryRunRoute,
  checkModelAllowlist,
  checkNodeRuntime,
  checkOutcomeConsent,
  checkStateDirWritable,
  renderDoctorReport,
  runDoctor,
  runPluginDoctor,
  type DoctorCheckResult,
  type DoctorCheckStatus,
  type DoctorReport,
  type PluginDoctorReport,
  type RunDoctorInput,
  type RunPluginDoctorInput,
} from './doctor.js';
export {
  type HokusaiDispatchPayload,
  type HokusaiFieldError,
  type HokusaiOutcome,
  type HokusaiValidationSuccess,
  type HokusaiTaskInput,
  type OutcomeResponse,
  type RouteRecommendation,
  type OutcomeResponseStatus,
  type RouteRequest,
  type RouteResponse,
  type TechnicalTaskRouterInputs,
  type TechnicalTaskRouterRequest,
  validateOutcomeReport,
  validateOutcomeResponse,
  validateRouteRequest,
  validateRouteResponse,
} from './schemas.js';
export {
  OUTCOME_REPORT_SCHEMA_VERSION,
  OutcomeReportBuildError,
  buildOutcomeReport,
  previewOutcomePayload,
  type BuildSummary,
  type CoarseBucket,
  type CompletionStatus,
  type OutcomeExtensions,
  type OutcomeReport,
  type OutcomeReportInput,
  type OutcomeValidationError,
  type TestSummary,
} from './outcome.js';
export {
  TASK_PACKET_SCHEMA_VERSION,
  TaskPacketBuildError,
  buildTaskPacket,
  validateTaskPacket,
  type HarnessContext,
  type ReasoningDepth,
  type RepositoryScale,
  type TaskFamily,
  type TaskPacket,
  type ValidationError,
  type ValidationResult,
} from './task-packet.js';
export {
  bucketRepositoryScale,
  classifyTaskFamily,
  inferReasoningDepth,
  summarizeFrameworkSignals,
  summarizeLanguageSignals,
  type ReasoningDepthInferenceInput,
  type TaskFamilyClassificationInput,
} from './task-signals.js';
export {
  REASONING_DEPTH_COMPLEXITY,
  TASK_FAMILY_TO_HOKUSAI_TYPE,
  deriveTaskDescriptor,
  normalizeComplexity,
  normalizeHokusaiLanguage,
  type TaskDescriptorFields,
  type TaskDescriptorInput,
  type TaskDescriptorSignals,
} from './task-descriptor.js';
export {
  ANTHROPIC_MODEL_PRICING,
  ANTHROPIC_MODEL_PRICING_AS_OF,
  computeActualCostUsd,
  resolveModelPrice,
  type ModelPrice,
  type TokenCostInput,
} from './pricing.js';
export {
  DEFAULT_SIDECAR_FRESHNESS_MS,
  captureCostBaseline,
  computeTranscriptCostUsd,
  encodeProjectDirKey,
  locateSessionTranscript,
  parseTranscriptUsageTotals,
  readSessionCostSidecar,
  resolveActualCostUsd,
  resolveClaudeConfigDir,
  resolveSidecarCostDiff,
  sessionCostSidecarPath,
  sessionTranscriptDir,
  type CostBaselineSnapshot,
  type CostResolutionRouteContext,
  type SessionCostSidecar,
  type SessionUsageFileSystem,
  type TranscriptUsageTotals,
} from './session-usage.js';
export {
  claudeCodeTaskPacketFixture,
  claudeCodeFailureOutcomeFixture,
  claudeCodeSuccessOutcomeFixture,
  codexAbandonedOutcomeFixture,
  codexSuccessOutcomeFixture,
  codexTaskPacketFixture,
  genericTaskPacketFixture,
  wavemillOverriddenOutcomeFixture,
  wavemillSuccessOutcomeFixture,
  wavemillTaskPacketFixture,
} from './fixtures/index.js';
export {
  FsLocalStore,
  InMemoryCorrelationStorage,
  InMemoryLocalStore,
  InvalidStoreIdError,
  RawPayloadRejectedError,
  StoreCorruptError,
  type CorrelationRecord,
  type CorrelationStorage,
  type LocalCorrelationRecord,
  type LocalStore,
  type PayloadHashRecord,
  type SubmissionAuditEntry,
  type SubmissionAuditKind,
  type SubmissionAuditStatus,
} from './storage.js';
export {
  conformanceChecks,
  conformanceFixtures,
  runAdapterConformance,
  type ConformanceCheck,
  type ConformanceSubject,
} from './conformance.js';
export * from './integration-kit/index.js';
export * from './plugin-commands/index.js';
export * from './contribution/index.js';
