export {
  DEFAULT_HOKUSAI_BASE_URL,
  HokusaiApiError,
  HokusaiAuthError,
  HokusaiClient,
  HokusaiDispatchBuilder,
  HokusaiDispatchError,
  HokusaiNetworkError,
  HokusaiRateLimitError,
  HokusaiValidationError,
  type FetchTransport,
  type HokusaiClientOptions,
  type HokusaiDispatchBuilderOptions,
  type HokusaiRequestOptions,
} from './client.js';
export {
  anonymizeText,
  DEFAULT_REDACTION_CONFIG,
  hashPayload,
  makePlaceholder,
  preview,
  redact,
  type AnonymizationOptions,
  type AnonymizedText,
  type CustomRedactionRule,
  type PreviewResult,
  type RedactionCategory,
  type RedactionConfig,
  type RedactionMatch,
  type RedactionMode,
  type RedactionRecord,
  type RedactionPattern,
  type RedactionResult,
} from './anonymization.js';
export {
  canReportOutcome,
  canRoute,
  isConsentGranted,
  resolveConsent,
  type ConsentConfig,
  type ConsentSettings,
  type ConsentScope,
  type ConsentSnapshot,
  type HokusaiApiConfig,
  type PayloadPreviewSettings,
  type RetentionPolicy,
} from './consent.js';
export type {
  AdapterError,
  AdapterResult,
  HarnessAdapter,
  HarnessConsentDecision,
  HarnessConsentDecisionState,
  HarnessConsentPromptRequest,
  HarnessConsentPrompter,
  HarnessDiscoveredModel,
  HarnessLocalStorage,
  HarnessModelDiscoveryRequest,
  HarnessModelHandoff,
  HarnessModelHandoffRequest,
  HarnessModelHandoffResult,
  HarnessModelMappingRequest,
  HarnessModelProvider,
  HarnessOutcomeCollectionRequest,
  HarnessOutcomeCollector,
  HarnessPayloadPreview,
  HarnessPayloadPreviewRequest,
  HarnessPayloadPreviewer,
  HarnessRecommendation,
  HarnessRecommendationDisplayRequest,
  HarnessRecommendationRenderer,
  HarnessTaskContext,
  HarnessTaskContextProvider,
  HarnessTaskContextRequest,
} from './adapter.js';
export {
  InMemoryModelRegistry,
  type ModelCapability,
  type ModelDefinition,
  type ModelRegistry,
  type ModelSelection,
} from './model-registry.js';
export {
  type HokusaiDispatchPayload,
  type HokusaiFieldError,
  type HokusaiOutcome,
  type HokusaiValidationSuccess,
  type HokusaiTaskInput,
  type OutcomeResponse,
  type OutcomeResponseStatus,
  type RouteRequest,
  type RouteResponse,
  validateOutcomeReport,
  validateOutcomeResponse,
  validateRouteRequest,
  validateRouteResponse,
} from './schemas.js';
export {
  OUTCOME_REPORT_SCHEMA_VERSION,
  OutcomeReportBuildError,
  buildOutcomeReport,
  previewOutcomePayload,
  type BuildSummary,
  type CoarseBucket,
  type CompletionStatus,
  type OutcomeExtensions,
  type OutcomeReport,
  type OutcomeReportInput,
  type OutcomeValidationError,
  type TestSummary,
} from './outcome.js';
export {
  TASK_PACKET_SCHEMA_VERSION,
  TaskPacketBuildError,
  buildTaskPacket,
  validateTaskPacket,
  type HarnessContext,
  type ReasoningDepth,
  type RepositoryScale,
  type TaskFamily,
  type TaskPacket,
  type ValidationError,
  type ValidationResult,
} from './task-packet.js';
export {
  claudeCodeTaskPacketFixture,
  claudeCodeFailureOutcomeFixture,
  claudeCodeSuccessOutcomeFixture,
  codexAbandonedOutcomeFixture,
  codexSuccessOutcomeFixture,
  codexTaskPacketFixture,
  genericTaskPacketFixture,
  wavemillOverriddenOutcomeFixture,
  wavemillSuccessOutcomeFixture,
  wavemillTaskPacketFixture,
} from './fixtures/index.js';
export {
  FsLocalStore,
  InMemoryCorrelationStorage,
  InMemoryLocalStore,
  InvalidStoreIdError,
  RawPayloadRejectedError,
  StoreCorruptError,
  type CorrelationRecord,
  type CorrelationStorage,
  type LocalCorrelationRecord,
  type LocalStore,
  type PayloadHashRecord,
  type SubmissionAuditEntry,
  type SubmissionAuditKind,
  type SubmissionAuditStatus,
} from './storage.js';
