/**
 * The Hokusai integration loop. **Do not edit this file when you fork.**
 *
 * The reusable implementation now lives in `@hokusai/core`. Forks should keep
 * their work in `../harness/` and import the shared loop rather than copying
 * it.
 *
 * @module hokusai/loop
 */

export {
  asHokusaiLoopClient,
  runHokusaiLoop,
  type HokusaiLoopClient,
  type HokusaiLoopOptions,
  type HokusaiLoopResult,
  type HostAdapter,
} from '@hokusai/core';

export const HARNESS_NAME = 'reference-harness';
export const HARNESS_SDK_VERSION = '0.2.0';
