/**
 * The Hokusai integration loop. **Do not edit this file when you fork.**
 *
 * Everything here is harness-agnostic: it holds the sequence, the privacy
 * boundary, and the identity threading that make a contribution row count. The
 * harness-specific parts live behind the `ReferenceHarnessAdapter` interface in
 * `../harness/`.
 *
 * The loop is:
 *
 *   1. collect task context      (yours)
 *   2. derive a task descriptor  (ours — categorical labels only, no raw text)
 *   3. anonymize the payload     (ours)
 *   4. route                     (ours — returns the inference_log_id)
 *   5. map the recommendation    (yours — your model ids)
 *   6. execute the task          (yours)
 *   7. price the run             (ours — tokens to actual_cost_usd)
 *   8. build + submit the row    (ours)
 *
 * @module hokusai/loop
 */

import {
  DEFAULT_REDACTION_CONFIG,
  HokusaiDispatchBuilder,
  InMemoryLocalStore,
  InMemoryModelRegistry,
  buildHarnessOutcomeRow,
  computeActualCostUsd,
  deriveTaskDescriptor,
  mapRecommendation,
  type ContributionAcceptedResponse,
  type HarnessOutcomeRowV1,
  type ModelDefinition,
  type TaskDescriptorFields,
  type TaskDescriptorSignals,
} from '@hokusai/core';
import type { ReferenceHarnessAdapter } from '../harness/index.js';
import type { MockHokusaiClient } from '../mock-client.js';

export const HARNESS_NAME = 'reference-harness';
export const HARNESS_SDK_VERSION = '0.2.0';

export interface HokusaiLoopOptions {
  adapter: ReferenceHarnessAdapter;
  client: MockHokusaiClient;
  models: ModelDefinition[];
  /** Repository signals used to derive descriptor buckets. Counts only. */
  repositorySignals?: TaskDescriptorSignals;
  /**
   * The run's cost ceiling. A row without a numeric budget cannot be scored for
   * success-under-budget, so the server classifies it `partial`. Omit this to
   * see that happen.
   */
  budgetUsd?: number;
  /**
   * Set false to submit without `actual_cost_usd` — the single most common
   * reason a real harness's rows land in `partial` instead of training.
   */
  reportCost?: boolean;
  redactionSalt: string;
  redactionSecret: string;
  idempotencyKey: string;
  log?: (line: string) => void;
}

export interface HokusaiLoopResult {
  /** The API's inference log id, threaded from route into the row. */
  inferenceLogId: string;
  taskDescriptor: TaskDescriptorFields;
  allowedModels: string[];
  selectedModel: string;
  promptPreview: string;
  redactionCount: number;
  actualCostUsd: number | undefined;
  row: HarnessOutcomeRowV1;
  response: ContributionAcceptedResponse;
  /** The server's authoritative tier for the submitted row, when reported. */
  fidelityTier: string | undefined;
}

function noop(): void {
  /* silent by default */
}

export async function runHokusaiLoop(
  options: HokusaiLoopOptions,
): Promise<HokusaiLoopResult> {
  const log = options.log ?? noop;
  const { adapter, client } = options;
  const registry = new InMemoryModelRegistry(options.models);
  const allowedModels = options.models.map((model) => model.id);
  const localStore = new InMemoryLocalStore();

  const dispatchBuilder = new HokusaiDispatchBuilder({
    consent: { subjectId: 'reference-harness', grantedScopes: ['task-execution'] },
    modelRegistry: registry,
    redactionConfig: {
      ...DEFAULT_REDACTION_CONFIG,
      salt: options.redactionSalt,
      customRules: [
        { category: 'secret', pattern: new RegExp(options.redactionSecret, 'g') },
      ],
    },
    clock: () => new Date('2026-06-08T00:00:00.000Z'),
  });

  // 1. Collect task context. Replace with your harness's real task input.
  log('[1/8] Collecting task context');
  const context = await adapter.collectTaskContext();

  // 2. Derive the task descriptor from the raw task text. This is what the
  //    router learns from. Only categorical labels leave this step: the raw
  //    text is read and discarded, never stored and never transmitted.
  log('[2/8] Deriving task descriptor (categorical labels only)');
  const derived = deriveTaskDescriptor({
    taskText: context.task.prompt,
    ...(options.repositorySignals ? { repositorySignals: options.repositorySignals } : {}),
  });
  // buildHarnessOutcomeRow rejects an empty descriptor. Fall back rather than
  // fabricate labels we did not actually derive.
  const taskDescriptor =
    Object.keys(derived).length > 0 ? derived : { task_type: 'unknown' };
  for (const [key, value] of Object.entries(taskDescriptor)) {
    log(`        ${key}: ${value}`);
  }

  // 3. Anonymize before anything crosses the network.
  log('[3/8] Previewing anonymized dispatch payload');
  const dispatchPayload = await dispatchBuilder.prepareDispatch(
    context.task,
    allowedModels[0] as string,
  );
  const preview = adapter.previewPayload(dispatchPayload);
  log(`        prompt:     ${preview.promptPreview}`);
  log(`        redactions: ${preview.redactionCount}`);

  // 4. Route. The response carries the API's inference_log_id.
  log('[4/8] Routing');
  const route = await client.route(dispatchPayload);
  const inferenceLogId = route.routeId;
  log(`        inference_log_id: ${inferenceLogId}`);
  await localStore.putCorrelation({
    correlationId: inferenceLogId,
    packetHash: 'reference-harness-packet-hash',
    createdAt: Date.parse('2026-06-08T00:00:00.000Z'),
  });

  // 5. Map the recommendation onto a model your harness can actually run.
  //    mapRecommendation falls back to a registry default when the router names
  //    a model you do not have — see the Pi / OpenHands notes in the README.
  log('[5/8] Mapping the recommendation to a local model');
  const recommended = route.recommendation?.model ?? allowedModels[0];
  const mapped = mapRecommendation({ model: recommended }, { registry });
  log(`        ${recommended} -> ${mapped.id}`);

  // 6. Execute. Yours. Return token counts so the run can be priced.
  log('[6/8] Executing the task');
  const execution = await adapter.executeTask({
    task: context.task,
    model: { id: mapped.id, provider: mapped.provider },
  });
  log(
    `        result: ${execution.completionResult}  ` +
      `in=${execution.inputTokens} out=${execution.outputTokens}`,
  );

  // 7. Price the run. Most harnesses have token counts but not a dollar figure;
  //    computeActualCostUsd turns one into the other. It returns undefined for
  //    an unknown model rather than fabricating a cost.
  log('[7/8] Deriving actual_cost_usd from token usage');
  const actualCostUsd =
    options.reportCost === false
      ? undefined
      : computeActualCostUsd({
          model: mapped.id,
          inputTokens: execution.inputTokens,
          outputTokens: execution.outputTokens,
          ...(execution.cacheCreationTokens !== undefined
            ? { cacheCreationTokens: execution.cacheCreationTokens }
            : {}),
          ...(execution.cacheReadTokens !== undefined
            ? { cacheReadTokens: execution.cacheReadTokens }
            : {}),
        });
  log(
    actualCostUsd === undefined
      ? '        actual_cost_usd: (omitted)'
      : `        actual_cost_usd: $${actualCostUsd.toFixed(6)}`,
  );

  // 8. Build the canonical row and submit it. `inferenceLogId` is what ties the
  //    row back to the routing decision — drop it and the row cannot be
  //    attributed, which is exactly the bug the Claude Code plugin once had.
  log('[8/8] Submitting the contribution row');
  const row = buildHarnessOutcomeRow({
    inferenceLogId,
    taskDescriptor,
    allowedModels,
    selectedModels: { coder: mapped.id, reviewer: mapped.id },
    completionResult: execution.completionResult,
    ...(options.budgetUsd !== undefined ? { budgetUsd: options.budgetUsd } : {}),
    ...(actualCostUsd !== undefined ? { actualCostUsd } : {}),
    wallClockSeconds: execution.wallClockSeconds,
    harness: HARNESS_NAME,
    sdkVersion: HARNESS_SDK_VERSION,
    taskId: context.task.id,
    observedAt: '2026-06-08T00:00:00.000Z',
  });

  const response = await client.submitContribution({
    rows: [row],
    metadata: { idempotency_key: options.idempotencyKey },
  });

  const fidelityTier = response.rowFidelityTiers?.[0];
  log(
    `        accepted=${String(response.accepted)} ` +
      `rowsAccepted=${String(response.rowsAccepted ?? 0)}`,
  );
  log(`        fidelity tier: ${fidelityTier ?? '(not reported by this API)'}`);

  return {
    inferenceLogId,
    taskDescriptor,
    allowedModels,
    selectedModel: mapped.id,
    promptPreview: preview.promptPreview,
    redactionCount: preview.redactionCount,
    actualCostUsd,
    row,
    response,
    fidelityTier,
  };
}
