/**
 * Wavemill parity goldens. GENERATED by scripts/generate-wavemill-task-cost-golden.mjs
 * from Wavemill @ a2d1cd6b (shared/lib/execution-economics.ts,
 * EXECUTION_ECONOMICS_SCHEMA_VERSION 1.0.0) over the matching task-cost
 * fixtures. Do not edit by hand; regenerate and review the diff.
 *
 * Each entry is the cost-relevant subset of the `EvalExecutionEconomics`
 * session Wavemill emits for that fixture, keyed by fixture name. Keys keep
 * Wavemill's camelCase on purpose: this is Wavemill's output, verbatim.
 *
 * @module fixtures/task-cost/wavemill-golden
 */

export interface WavemillGoldenSession {
  providerContractVersion: string;
  harness: 'claude-code' | 'codex';
  usage: {
    inputTokens: number | null;
    outputTokens: number | null;
    cacheReadTokens: number | null;
    cacheWriteTokens: number | null;
    reasoningTokens: number | null;
  };
  actualCostUsd: number | null;
  estimatedCostUsd: number | null;
  costSource: 'provider_reported' | 'local_estimate' | 'none';
  pricingRevision: string | null;
  pricingTimestamp: string | null;
  coverage: 'complete' | 'partial' | 'unavailable' | 'known_zero';
  turnCount: number;
  modelSegments: Array<{ model: string; turnCount: number }>;
}

export const wavemillGoldens: Readonly<Record<string, WavemillGoldenSession>> = {
  "claude-code-simple": {
    "providerContractVersion": "claude-code/1",
    "harness": "claude-code",
    "usage": {
      "inputTokens": 4500,
      "outputTokens": 2300,
      "cacheReadTokens": 0,
      "cacheWriteTokens": 0,
      "reasoningTokens": 0
    },
    "actualCostUsd": 0.0489,
    "estimatedCostUsd": 0.048,
    "costSource": "provider_reported",
    "pricingRevision": "2026-07-15",
    "pricingTimestamp": "2026-01-01T00:03:00.000Z",
    "coverage": "complete",
    "turnCount": 3,
    "modelSegments": [
      {
        "model": "claude-sonnet-5",
        "turnCount": 3
      }
    ]
  },
  "claude-code-model-switch": {
    "providerContractVersion": "claude-code/1",
    "harness": "claude-code",
    "usage": {
      "inputTokens": 10000,
      "outputTokens": 3900,
      "cacheReadTokens": 0,
      "cacheWriteTokens": 0,
      "reasoningTokens": 0
    },
    "actualCostUsd": null,
    "estimatedCostUsd": 0.1185,
    "costSource": "local_estimate",
    "pricingRevision": "2026-07-15",
    "pricingTimestamp": "2026-01-01T00:04:00.000Z",
    "coverage": "complete",
    "turnCount": 4,
    "modelSegments": [
      {
        "model": "claude-opus-4-8",
        "turnCount": 2
      },
      {
        "model": "claude-sonnet-5",
        "turnCount": 2
      }
    ]
  },
  "claude-code-cache-tiers": {
    "providerContractVersion": "claude-code/1",
    "harness": "claude-code",
    "usage": {
      "inputTokens": 1500,
      "outputTokens": 1500,
      "cacheReadTokens": 16000,
      "cacheWriteTokens": 9000,
      "reasoningTokens": 0
    },
    "actualCostUsd": null,
    "estimatedCostUsd": 0.10925000000000001,
    "costSource": "local_estimate",
    "pricingRevision": "2026-07-15",
    "pricingTimestamp": "2026-01-01T00:03:00.000Z",
    "coverage": "complete",
    "turnCount": 3,
    "modelSegments": [
      {
        "model": "claude-opus-4-8",
        "turnCount": 3
      }
    ]
  },
  "codex-simple": {
    "providerContractVersion": "codex/1",
    "harness": "codex",
    "usage": {
      "inputTokens": 5000,
      "outputTokens": 1500,
      "cacheReadTokens": 0,
      "cacheWriteTokens": 0,
      "reasoningTokens": 450
    },
    "actualCostUsd": null,
    "estimatedCostUsd": 0.025750000000000002,
    "costSource": "local_estimate",
    "pricingRevision": "2026-07-15",
    "pricingTimestamp": "2026-01-01T00:02:00.000Z",
    "coverage": "complete",
    "turnCount": 2,
    "modelSegments": [
      {
        "model": "gpt-5-codex",
        "turnCount": 2
      }
    ]
  },
  "codex-unknown-pricing": {
    "providerContractVersion": "codex/1",
    "harness": "codex",
    "usage": {
      "inputTokens": 3000,
      "outputTokens": 1100,
      "cacheReadTokens": 0,
      "cacheWriteTokens": 0,
      "reasoningTokens": 0
    },
    "actualCostUsd": null,
    "estimatedCostUsd": null,
    "costSource": "none",
    "pricingRevision": null,
    "pricingTimestamp": null,
    "coverage": "partial",
    "turnCount": 2,
    "modelSegments": [
      {
        "model": "gpt-5",
        "turnCount": 1
      },
      {
        "model": "codex-unlisted-model",
        "turnCount": 1
      }
    ]
  },
  "codex-provider-override": {
    "providerContractVersion": "codex/1",
    "harness": "codex",
    "usage": {
      "inputTokens": 3000,
      "outputTokens": 1300,
      "cacheReadTokens": 0,
      "cacheWriteTokens": 0,
      "reasoningTokens": 0
    },
    "actualCostUsd": 0.0163,
    "estimatedCostUsd": 0.01675,
    "costSource": "provider_reported",
    "pricingRevision": "2026-07-15",
    "pricingTimestamp": "2026-01-01T00:02:00.000Z",
    "coverage": "complete",
    "turnCount": 2,
    "modelSegments": [
      {
        "model": "gpt-5",
        "turnCount": 2
      }
    ]
  },
  "partial-usage": {
    "providerContractVersion": "codex/1",
    "harness": "codex",
    "usage": {
      "inputTokens": 3000,
      "outputTokens": 500,
      "cacheReadTokens": 0,
      "cacheWriteTokens": 0,
      "reasoningTokens": 0
    },
    "actualCostUsd": null,
    "estimatedCostUsd": 0.00875,
    "costSource": "local_estimate",
    "pricingRevision": "2026-07-15",
    "pricingTimestamp": "2026-01-01T00:02:00.000Z",
    "coverage": "complete",
    "turnCount": 2,
    "modelSegments": [
      {
        "model": "gpt-5",
        "turnCount": 2
      }
    ]
  },
  "wavemill-parity": {
    "providerContractVersion": "claude-code/1",
    "harness": "claude-code",
    "usage": {
      "inputTokens": 6700,
      "outputTokens": 2600,
      "cacheReadTokens": 47000,
      "cacheWriteTokens": 3500,
      "reasoningTokens": 300
    },
    "actualCostUsd": 0.1233,
    "estimatedCostUsd": 0.122625,
    "costSource": "provider_reported",
    "pricingRevision": "2026-07-15",
    "pricingTimestamp": "2026-01-01T00:03:00.000Z",
    "coverage": "complete",
    "turnCount": 3,
    "modelSegments": [
      {
        "model": "claude-opus-4-8",
        "turnCount": 2
      },
      {
        "model": "claude-sonnet-4-6",
        "turnCount": 1
      }
    ]
  }
};
